CREATE DATABASE IF NOT EXISTS attendance_system;
USE attendance_system;

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    roll_no INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    branch ENUM('AIML', 'AIDS') NOT NULL,
    UNIQUE KEY unique_student (roll_no, branch)
);

CREATE TABLE IF NOT EXISTS subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT IGNORE INTO subjects (name) VALUES ('OOP'),('MATHS'),('DSA'),('CN'),('FAI/ML');

CREATE TABLE IF NOT EXISTS attendance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    subject VARCHAR(100) NOT NULL,
    slot_no INT NOT NULL,
    branch ENUM('AIML', 'AIDS') NOT NULL,
    roll_no INT NOT NULL,
    status ENUM('absent', 'library') NOT NULL DEFAULT 'absent',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AIML Students
INSERT IGNORE INTO students (roll_no, name, branch) VALUES
(1,'TELAGATHOTI NAVA TEJA','AIML'),
(2,'DHOLAKIYA RAJ HARESHBHAI','AIML'),
(3,'KOTA DINESH MR. SURENDRA','AIML'),
(4,'KURAKULA MANIVENKATA TEJA','AIML'),
(5,'NEELAM MANIKANTA','AIML'),
(6,'PEDHADIYA KHODIDAS JAMANBHAI','AIML'),
(7,'SHAMDAR RAMIZSHA MAHEBUBSHA','AIML'),
(8,'MOMIN SAID MEER','AIML'),
(9,'SHAIK NEMALIPURI MAHMAD NAZEER','AIML'),
(10,'CHEVALA NAGA NARAHARI BABU','AIML'),
(11,'MATHANGI MANEESH KUMAR','AIML'),
(12,'PATRA SIDDHARDHA','AIML'),
(13,'VEMANA PREM KUMAR','AIML'),
(14,'JOSHI MRUTYUNJAY AMITBHAI','AIML'),
(15,'SAKHRELIYA VANSHIL SANJAYBHAI','AIML'),
(16,'VAMAJA RAJ ISHVARBHAI','AIML'),
(17,'MAKADIYA KRENSI RAMNIKBHAI','AIML'),
(18,'RATHOD SWATI RATILAL','AIML'),
(19,'KADAM HARSH ANKUSHBHAI','AIML'),
(20,'PRINCEKUMAR SUTHAR','AIML'),
(21,'PANDUGU DIKSHITH','AIML'),
(22,'CHENNAIHGARI SPANDANA','AIML');

-- AIDS Students
INSERT IGNORE INTO students (roll_no, name, branch) VALUES
(1,'CHANDANA CHARANYA RATNA PRIYA','AIDS'),
(2,'DASARI ANUHYA DEVI','AIDS'),
(3,'GADENAVENI SHIVA','AIDS'),
(4,'GARAPATI SANJANA PRABHA DEVI','AIDS'),
(5,'KARIPI SAI DURGA PRAVEEN','AIDS'),
(6,'KOTTA BALAJI','AIDS'),
(7,'LINGALA HARINI','AIDS'),
(8,'MEKALA DIVAKAR REDDY','AIDS'),
(9,'POLINA MOHITHA','AIDS'),
(10,'SABBINENI SAGAR','AIDS'),
(11,'SHAIK HANEEF','AIDS'),
(12,'JITENDER TAMMINANA','AIDS'),
(13,'TIRUMALA RAJU BALA VENKATA PAVAN VARMA','AIDS'),
(14,'VALLEPALLI VASANTH RAJ','AIDS'),
(15,'BADE ASMITHA SRIJA','AIDS'),
(16,'CHAKALI KOUSHIK BABU','AIDS'),
(17,'MADIRA SAI THRIVEDI','AIDS'),
(18,'NILLA SUVARSHA','AIDS'),
(19,'PASYAVULA BHARAT RAMA SWAMI','AIDS'),
(20,'SALA NAGA VENKATA NIKHIL','AIDS'),
(21,'TALLAPALLE TEJOVANTH VENKATA SAI RAMESH','AIDS'),
(22,'SATYA KESHIK TUNGALA','AIDS'),
(23,'BADAM DHEEMANTH REDDY','AIDS'),
(24,'MADIREDDY LAKSHMI PRASANNA','AIDS'),
(25,'PALLE NITHIN','AIDS'),
(26,'PALLE NITHISH','AIDS'),
(27,'PATHI CHARITHA SRI','AIDS'),
(28,'RAAVI NETHAJI','AIDS'),
(29,'BORAD KRISH HARESHBHAI','AIDS'),
(30,'BURRI SRINU','AIDS'),
(31,'GURRAM NAGA PHANEENDRA KUMAR','AIDS'),
(32,'MOLAGAVALLI DINESH PATEL','AIDS'),
(33,'PARASA PAVAN KUMAR','AIDS'),
(34,'PUSULURI HEMANTHA LAKSHMI GOPIKA','AIDS'),
(35,'BYALLA VISHNUVARDHAN','AIDS'),
(36,'DAGI KISHOR','AIDS'),
(37,'MURABOYINA MADHU SPANDHANA','AIDS'),
(38,'PERAM SHYAM SUNDARA REDDY','AIDS'),
(39,'RALLABANDI VENKATA SUPRAJA','AIDS'),
(40,'BOSIGARI CHANDRA JAHNAVI','AIDS'),
(41,'CHIRALA GANESH','AIDS'),
(42,'PARLAPU VAISHNAVI','AIDS'),
(43,'SHAIK ISHFAAQ','AIDS'),
(44,'GANGIREDDY RAKESH REDDY','AIDS'),
(45,'KANAPARTHI ANURAG','AIDS'),
(46,'MANGALA ARCHITHA','AIDS'),
(47,'VELUGURI KARTHIKEYA','AIDS'),
(48,'GRANDHI NAGA JYOTHI','AIDS'),
(49,'ATHUPAKAM LOKESH REDDY','AIDS'),
(50,'GANDHAM JEEVAN','AIDS'),
(51,'MEENA VENKATA RAGHUNANDAN','AIDS'),
(52,'GOHIL TANISH KETANBHAI','AIDS'),
(53,'BHANDERI NENSEE MAHENDRABHAI','AIDS'),
(54,'GUMMA VENKATA SRINIVASULU','AIDS'),
(55,'KURUBA PUNITH SAI','AIDS'),
(56,'CHAVDA MADHAV RAMESHBHAI','AIDS'),
(57,'PARMAR MEET RAJESHBHAI','AIDS');
